# Generated by Django 4.2.30 on 2026-10-02 23:39

import core.utils
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import provider_contract.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claim', '0036_alter_claim_admin_delete_claimadmin'),
        ('location', '0019_alter_location_code'),
        ('provider_contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalClaimScopeViolation',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('service_code', models.CharField(db_column='ServCode', max_length=6)),
                ('date_of_service', models.DateTimeField(blank=True, db_column='DateOfService', null=True)),
                ('reason_code', models.CharField(choices=[('NOT_EMPANELLED', 'Provider not empanelled'), ('OUTSIDE_SCOPE', 'Service outside contracted scope'), ('CONTRACT_EXPIRED', 'Contract expired at date of service'), ('NO_ACTIVE_CONTRACT', 'No active contract on that date'), ('LICENSE_EXPIRED', 'Licence or accreditation expired'), ('NO_FEE_MATCH', 'No matching fee for this service'), ('FEE_MISMATCH', 'Claimed amount differs from contract fee')], db_column='ReasonCode', max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('BLOCKING', 'Blocking')], db_column='Severity', default='WARNING', max_length=10)),
                ('details', models.JSONField(blank=True, db_column='Details', null=True)),
                ('is_resolved', models.BooleanField(db_column='IsResolved', default=False)),
                ('date_resolved', models.DateTimeField(blank=True, db_column='DateResolved', null=True)),
                ('resolution', models.CharField(blank=True, db_column='Resolution', max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('claim', models.ForeignKey(blank=True, db_column='ClaimID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='claim.claim')),
                ('claim_service', models.ForeignKey(blank=True, db_column='ClaimServiceID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='claim.claimservice')),
                ('contract', models.ForeignKey(blank=True, db_column='ContractUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='provider_contract.providercontract')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, db_column='HfID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.healthfacility')),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='ReviewedByUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical claim scope violation',
                'verbose_name_plural': 'historical claim scope violations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ClaimScopeViolation',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', models.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', models.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('service_code', models.CharField(db_column='ServCode', max_length=6)),
                ('date_of_service', models.DateTimeField(blank=True, db_column='DateOfService', null=True)),
                ('reason_code', models.CharField(choices=[('NOT_EMPANELLED', 'Provider not empanelled'), ('OUTSIDE_SCOPE', 'Service outside contracted scope'), ('CONTRACT_EXPIRED', 'Contract expired at date of service'), ('NO_ACTIVE_CONTRACT', 'No active contract on that date'), ('LICENSE_EXPIRED', 'Licence or accreditation expired'), ('NO_FEE_MATCH', 'No matching fee for this service'), ('FEE_MISMATCH', 'Claimed amount differs from contract fee')], db_column='ReasonCode', max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('BLOCKING', 'Blocking')], db_column='Severity', default='WARNING', max_length=10)),
                ('details', models.JSONField(blank=True, db_column='Details', null=True)),
                ('is_resolved', models.BooleanField(db_column='IsResolved', default=False)),
                ('date_resolved', models.DateTimeField(blank=True, db_column='DateResolved', null=True)),
                ('resolution', models.CharField(blank=True, db_column='Resolution', max_length=255, null=True)),
                ('claim', models.ForeignKey(db_column='ClaimID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='provider_contract_violations', to='claim.claim')),
                ('claim_service', models.ForeignKey(blank=True, db_column='ClaimServiceID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='claim.claimservice')),
                ('contract', models.ForeignKey(blank=True, db_column='ContractUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='violations', to='provider_contract.providercontract')),
                ('provider', models.ForeignKey(db_column='HfID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.healthfacility')),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='ReviewedByUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider_contract_ClaimScopeViolation',
                'ordering': ['-date_created'],
                'managed': True,
                'indexes': [models.Index(fields=['claim', 'reason_code'], name='pce_violation_claim_reason'), models.Index(fields=['provider', 'date_of_service'], name='pce_violation_provider_date')],
            },
            bases=(provider_contract.models.ProviderContractQueryMixin, dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='claimscopeviolation',
            constraint=models.UniqueConstraint(fields=('claim', 'claim_service', 'reason_code'), name='pce_violation_unique'),
        ),
    ]
