# Generated by Django 4.2.30 on 2026-10-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_contract', '0003_backfill_contracts_from_health_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprovidercontract',
            name='contract_number',
            field=models.CharField(db_column='ContractNo', max_length=30),
        ),
        migrations.AlterField(
            model_name='providercontract',
            name='contract_number',
            field=models.CharField(db_column='ContractNo', max_length=30),
        ),
    ]
